version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: quiz_postgres
    environment:
      POSTGRES_USER: quiz_user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: quiz_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
